//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsInGroups
    {
        public System.Guid StudentID { get; set; }
        public System.Guid GroupID { get; set; }
        public int PaymentFormID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Students Students { get; set; }
    }
}
